name: "Lint Markdown files"

on: [pull_request]

jobs:
  lint-files:
    runs-on: ubuntu-latest
    steps:
      - name: Setup linkstatus, mdspell and write-good
        run: |
          sudo apt-get update --fix-missing
          sudo apt install nodejs
          npm config set prefix=${HOME}/.node
          echo "::add-path::${HOME}/.node/bin"
          npm install markdown-spellcheck -g
          npm install write-good -g
          python3 -m pip install linkstatus --user
          echo "::add-path::${HOME}/.local/bin"

      - name: Checkout to changes
        uses: actions/checkout@v2

      - name: Fetch the target branch
        run: |
          git fetch --prune --depth=1 origin \
            refs/heads/${{ github.base_ref }}:${{ github.base_ref }}

      - name: Affected Files
        run: |
          affected_files="$(git diff ${{ github.base_ref }} HEAD \
            --name-only --diff-filter=d | tr '\n' ' ')"
          echo "::set-env name=AFFECTED_FILES::${affected_files}"

      - name: Check Links
        run: "linkstatus --recursive --timeout 10 --retry 5 ${AFFECTED_FILES}"

      - name: Spelling Suggestions
        run: "mdspell -r -n -a --en-us ${AFFECTED_FILES} || true"

      - name: Good Writing Suggestions
        run: "write-good ${AFFECTED_FILES} || true"
